function build(sessionId, publicBaseUrl) {
  const perceiverUrl = `${publicBaseUrl}/perceiver`;

  const scriptCode = `
(function() {
  // ComplyNow Traffic Capture
  // Session: ${sessionId}
  // Do not modify — auto-generated

  const SESSION_ID   = "${sessionId}";
  const PERCEIVER    = "${perceiverUrl}";
  const MAX_BODY     = 5000;

  function sendEntry(entry) {
    fetch(PERCEIVER, {
      method:  "POST",
      headers: { "Content-Type": "application/json" },
      body:    JSON.stringify(entry),
    }).catch(() => {});
  }

  function headersToDict(headers) {
    const dict = {};
    if (!headers) return dict;
    if (headers.entries) {
      for (const [k, v] of headers.entries()) dict[k] = v;
    } else if (Array.isArray(headers)) {
      headers.forEach(h => dict[h.name] = h.value);
    }
    return dict;
  }

  // Intercept fetch()
  const _origFetch = window.fetch.bind(window);
  window.fetch = async function(input, init) {
    const startTime = Date.now();
    const url    = typeof input === "string" ? input : input.url;
    const method = (init && init.method) || "GET";

    let requestBody = null;
    if (init && init.body) {
      try {
        requestBody = typeof init.body === "string"
          ? init.body.substring(0, MAX_BODY)
          : JSON.stringify(init.body).substring(0, MAX_BODY);
      } catch(e) {}
    }

    const response = await _origFetch(input, init);
    const clone    = response.clone();
    const duration = Date.now() - startTime;

    clone.text().then(function(body) {
      sendEntry({
        session_id:       SESSION_ID,
        url:              url,
        method:           method,
        status:           response.status,
        request_headers:  headersToDict(init && init.headers),
        response_headers: headersToDict(response.headers),
        request_body:     requestBody,
        response_body:    body.substring(0, MAX_BODY),
        timestamp:        new Date().toISOString(),
        duration_ms:      duration,
      });
    }).catch(() => {});

    return response;
  };

  // Intercept XMLHttpRequest
  const _origOpen = XMLHttpRequest.prototype.open;
  const _origSend = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function(method, url) {
    this._complynow_method = method;
    this._complynow_url    = url;
    this._complynow_start  = Date.now();
    return _origOpen.apply(this, arguments);
  };

  XMLHttpRequest.prototype.send = function(body) {
    const xhr = this;
    xhr.addEventListener("load", function() {
      sendEntry({
        session_id:       SESSION_ID,
        url:              xhr._complynow_url    || "",
        method:           xhr._complynow_method || "GET",
        status:           xhr.status,
        request_headers:  {},
        response_headers: {},
        request_body:     body
          ? String(body).substring(0, MAX_BODY) : null,
        response_body:    xhr.responseText
          ? xhr.responseText.substring(0, MAX_BODY) : null,
        timestamp:        new Date().toISOString(),
        duration_ms:      Date.now() - (xhr._complynow_start || 0),
      });
    });
    return _origSend.apply(this, arguments);
  };

  console.log("[ComplyNow] Traffic capture active. Session:", SESSION_ID);
})();
`;

  return {
    "version": "2",
    "rules": [
      {
        "name":     `ComplyNow Capture — ${sessionId}`,
        "ruleType": "SCRIPT",
        "status":   "Active",
        "pairs": [
          {
            "source": {
              "key":      "Url",
              "operator": "Contains",
              "value":    ".",
            },
            "scripts": [
              {
                "type":      "code",
                "codeType":  "js",
                "loadTime":  "afterPageLoad",
                "value":     scriptCode,
              }
            ],
          }
        ],
        "description": `Auto-generated by ComplyNow. Forwards traffic to compliance analysis. Session: ${sessionId}`,
      }
    ],
    "groups": [
      {
        "id":     "complynow-capture",
        "name":   "ComplyNow — Traffic Capture",
        "status": "Active",
      }
    ]
  };
}

module.exports = { build };
